DISTRO ="Mysmpd"
DISTRO_NAME ="Mysmpd (My smart motion project distribution)"
DISTRO_VERSION = "2026.02.27"
DISTRO_CODENAME = "kirkstone"
INIT_MANAGER ="sysvinit"

require conf/distro/include/no-gplv3.inc
require conf/distro/include/security_flags.inc
TCLIBCAPPEND = ""
DISTRO_FEATURES = "\
acl \
argp \
ext2 \ 
ipv4 \
ipv6 \ 
pcmcia \
usbgadget \
usbhost \
wifi \
xattr \
zeroconf \
vfat \
seccomp \
"

